# Generated by Django 4.2.6 on 2024-12-19 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MentalHealthAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question1", models.CharField(max_length=50)),
                ("question2", models.CharField(max_length=50)),
                ("question3", models.CharField(max_length=50)),
                ("question4", models.CharField(max_length=50)),
                ("question5", models.CharField(max_length=50)),
                ("question6", models.CharField(max_length=50)),
                ("question7", models.CharField(max_length=50)),
                ("question8", models.CharField(max_length=50)),
                ("question9", models.CharField(max_length=50)),
                ("question10", models.CharField(max_length=50)),
                ("question11", models.CharField(max_length=50)),
                ("question12", models.CharField(max_length=50)),
                ("question13", models.CharField(max_length=50)),
                ("question14", models.CharField(max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
